# -*- coding: utf-8 -*-
"""Fossology-GSoc'25-LicenseDetectionLLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10RlTQP-jhErV-2W9K-iUAxfI6r5MoZCy
"""

# Install dependencies
!pip install transformers sentence-transformers faiss-cpu requests tqdm --quiet

# Imports
import requests
import numpy as np
import faiss
from tqdm import tqdm
from sentence_transformers import SentenceTransformer

# Step 1: Load strong embedding model
model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

# Step 2: Fetch SPDX licenses
url = "https://raw.githubusercontent.com/spdx/license-list-data/main/json/licenses.json"
response = requests.get(url)
data = response.json()

license_texts = []
license_ids = []

for entry in tqdm(data["licenses"]):
    license_id = entry["licenseId"]
    # Some licenses have 'isDeprecatedLicenseId' or are templates
    if entry.get("isDeprecatedLicenseId", False):
        continue

    # Try fetching full license text
    license_url = f"https://raw.githubusercontent.com/spdx/license-list-data/main/text/{license_id}.txt"
    license_resp = requests.get(license_url)
    if license_resp.status_code == 200:
        license_text = license_resp.text.strip()
        license_texts.append(license_text)
        license_ids.append(license_id)

# Step 3: Embed and index with FAISS
embeddings = model.encode(license_texts, show_progress_bar=True, convert_to_numpy=True)
embeddings = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)  # normalize

index = faiss.IndexFlatIP(embeddings.shape[1])  # cosine similarity
index.add(embeddings)

# Step 4: Define retrieval function
def retrieve_license(input_text, k=3, threshold=0.75):
    embedding = model.encode([input_text], convert_to_numpy=True)
    embedding = embedding / np.linalg.norm(embedding)

    scores, indices = index.search(embedding, k)

    results = []
    for i in range(k):
        score = float(scores[0][i])
        if score >= threshold:
            results.append((license_ids[indices[0][i]], score))
    return results

# Step 5: Sample Input 1
sample_input_1 = """
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
"""

results = retrieve_license(sample_input_1)
for license_id, score in results:
    print(f"License: {license_id}, Cosine Similarity Score: {score:.4f}")

# Step 5: Sample Input 2
sample_input_2 = """
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
"""

results = retrieve_license(sample_input_2)
for license_id, score in results:
    print(f"License: {license_id}, Cosine Similarity Score: {score:.4f}")

# Step 5: Sample Input 3
sample_input_3 = """
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files...
"""

results = retrieve_license(sample_input_3)
for license_id, score in results:
    print(f"License: {license_id}, Cosine Similarity Score: {score:.4f}")

# Step 5: Sample Input 4
sample_input_4 = """
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation.
"""

results = retrieve_license(sample_input_4)
for license_id, score in results:
    print(f"License: {license_id}, Cosine Similarity Score: {score:.4f}")